CREATE TABLE Event(
    eventId LONG AUTO_INCREMENT PRIMARY KEY,
    todo VARCHAR(300) NOT NULL ,
    name VARCHAR(50) NOT NULL ,
    password VARCHAR(255) NOT NULL ,
    createDay DATE NOT NULL,
    updateDay DATE NOT NULL
);